# Uncomment the next line to define a global platform for your project
platform :ios, 13.2

source 'https://github.com/CocoaPods/Specs.git'

target 'marvel-app' do

  use_frameworks!
  inhibit_all_warnings!
 
  pod 'AlamofireImage', '~> 3.5.2'
  pod 'AlamofireObjectMapper', '~> 5.2.1'
  pod 'Localize-Swift', '~> 3.1.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  pod 'SVProgressHUD', '2.2.5'
end
